"""
Parity and regression tests for metrics extraction (Phase 4).

These tests verify that the metrics.py implementation produces
bit-exact identical values to the metrics attached to StrategyResult
instances generated by the backtest engine.
"""
from dataclasses import asdict
from pathlib import Path
import math
import json
import sys

import numpy as np
import pandas as pd
import pytest

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from core.backtest_engine import (  # noqa: E402
    StrategyResult,
    TradeRecord,
    load_data,
    prepare_dataset_with_warmup,
)
import core.metrics as metrics_module  # noqa: E402
from core.metrics import (  # noqa: E402
    _advanced_metric_view,
    _calculate_monthly_returns,
    calculate_basic,
    calculate_advanced,
    _calculate_r2_consistency,
    _calculate_sharpe_ratio_value,
    _calculate_sqn_value,
    _calculate_ulcer_index_value,
    _welford_mean_m2,
)
from strategies.s01_trailing_ma.strategy import S01Params, S01TrailingMA  # noqa: E402

PROJECT_ROOT = Path(__file__).parent.parent
DATA_PATH = PROJECT_ROOT / "data" / "raw" / "OKX_LINKUSDT.P, 15 2025.05.01-2025.11.20.csv"
BASELINE_PATH = PROJECT_ROOT / "data" / "baseline" / "s01_metrics.json"


@pytest.fixture(scope="module")
def test_data():
    df = load_data(str(DATA_PATH))
    return df


@pytest.fixture(scope="module")
def baseline_params():
    with open(BASELINE_PATH, "r") as f:
        baseline = json.load(f)
    return baseline["parameters"], baseline


@pytest.fixture(scope="module")
def test_result(test_data, baseline_params):
    params_dict, baseline = baseline_params
    params = S01Params.from_dict(params_dict)

    start_ts = pd.Timestamp(params_dict["start"], tz="UTC")
    end_ts = pd.Timestamp(params_dict["end"], tz="UTC")
    warmup_bars = baseline["warmup_bars"]

    df_prepared, trade_start_idx = prepare_dataset_with_warmup(
        test_data, start_ts, end_ts, warmup_bars
    )

    result = S01TrailingMA.run(df_prepared, asdict(params), trade_start_idx)
    return result


class TestDatasetPreparationDateRange:
    @staticmethod
    def _frame():
        index = pd.date_range("2025-01-01", periods=5, freq="D", tz="UTC")
        return pd.DataFrame({"Close": range(5)}, index=index)

    def test_inverted_closed_range_fails_before_index_processing(self):
        empty = self._frame().iloc[0:0]

        with pytest.raises(ValueError, match=r"^start must not be after end\.$"):
            prepare_dataset_with_warmup(
                empty,
                pd.Timestamp("2025-01-04", tz="UTC"),
                pd.Timestamp("2025-01-03", tz="UTC"),
                1,
            )

    @pytest.mark.parametrize(
        ("start_day", "end_day", "expected_days", "expected_trade_start"),
        [
            (3, 4, [2, 3, 4], 1),
            (3, 3, [2, 3], 1),
            (None, 3, [1, 2, 3], 0),
            (3, None, [2, 3, 4, 5], 1),
            (None, None, [1, 2, 3, 4, 5], 0),
        ],
    )
    def test_ordered_equal_and_open_ended_ranges_are_unchanged(
        self,
        start_day,
        end_day,
        expected_days,
        expected_trade_start,
    ):
        frame = self._frame()
        start = (
            pd.Timestamp(f"2025-01-{start_day:02d}", tz="UTC")
            if start_day is not None
            else None
        )
        end = (
            pd.Timestamp(f"2025-01-{end_day:02d}", tz="UTC")
            if end_day is not None
            else None
        )

        prepared, trade_start_idx = prepare_dataset_with_warmup(
            frame,
            start,
            end,
            1,
        )

        assert prepared.index.day.tolist() == expected_days
        assert trade_start_idx == expected_trade_start


class TestMetricsParity:
    """Test parity between StrategyResult values and metrics module."""

    def test_basic_net_profit_matches(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.net_profit == pytest.approx(test_result.net_profit)
        assert basic.net_profit_pct == pytest.approx(test_result.net_profit_pct)

    def test_basic_drawdown_matches(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.max_drawdown == pytest.approx(test_result.max_drawdown)
        assert basic.max_drawdown_pct == pytest.approx(test_result.max_drawdown_pct)

    def test_basic_trade_counts_match(self, test_result):
        basic = calculate_basic(test_result)
        assert basic.total_trades == test_result.total_trades
        assert basic.winning_trades == test_result.winning_trades
        assert basic.losing_trades == test_result.losing_trades

    def test_advanced_profit_factor_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.profit_factor == pytest.approx(test_result.profit_factor)

    def test_advanced_romad_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.romad == pytest.approx(test_result.romad)

    def test_advanced_ulcer_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.ulcer_index == pytest.approx(test_result.ulcer_index)

    def test_advanced_sqn_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        if test_result.sqn is None:
            assert advanced.sqn is None
        else:
            assert advanced.sqn == pytest.approx(test_result.sqn)

    def test_advanced_consistency_matches(self, test_result):
        advanced = calculate_advanced(test_result)
        assert advanced.consistency_score == pytest.approx(test_result.consistency_score)


class TestMetricsEdgeCases:
    """Test metrics calculation with edge scenarios."""

    def test_zero_trades(self):
        result = StrategyResult(
            trades=[],
            equity_curve=[10000.0],
            balance_curve=[10000.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.total_trades == 0
        assert basic.net_profit_pct == 0.0
        assert basic.win_rate == 0.0
        assert basic.avg_win == 0.0
        assert basic.avg_loss == 0.0
        assert advanced.profit_factor is None
        assert advanced.sharpe_ratio is None

    def test_all_winning_trades(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=110.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-03", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-04", tz="UTC"),
                entry_price=110.0,
                exit_price=120.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-05", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-06", tz="UTC"),
                entry_price=120.0,
                exit_price=130.0,
                size=1.0,
                net_pnl=10.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[10000, 10010, 10020, 10030],
            balance_curve=[10000, 10010, 10020, 10030],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
                pd.Timestamp("2025-01-04", tz="UTC"),
                pd.Timestamp("2025-01-06", tz="UTC"),
            ],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.total_trades == 3
        assert basic.winning_trades == 3
        assert basic.losing_trades == 0
        assert basic.win_rate == 100.0
        assert basic.gross_profit == 30.0
        assert basic.gross_loss == 0.0
        assert math.isinf(advanced.profit_factor)

    def test_all_losing_trades(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=90.0,
                size=1.0,
                net_pnl=-10.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[10000, 9990],
            balance_curve=[10000, 9990],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
            ],
        )

        basic = calculate_basic(result)
        advanced = calculate_advanced(result)

        assert basic.winning_trades == 0
        assert basic.losing_trades == 1
        assert basic.win_rate == 0.0
        assert advanced.profit_factor == 0.0

    def test_max_consecutive_losses_includes_breakeven(self):
        trades = [
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-01", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-02", tz="UTC"),
                entry_price=100.0,
                exit_price=95.0,
                size=1.0,
                net_pnl=-5.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-03", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-04", tz="UTC"),
                entry_price=95.0,
                exit_price=95.0,
                size=1.0,
                net_pnl=0.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-05", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-06", tz="UTC"),
                entry_price=95.0,
                exit_price=90.0,
                size=1.0,
                net_pnl=-5.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-07", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-08", tz="UTC"),
                entry_price=90.0,
                exit_price=100.0,
                size=1.0,
                net_pnl=10.0,
            ),
            TradeRecord(
                direction="Long",
                entry_time=pd.Timestamp("2025-01-09", tz="UTC"),
                exit_time=pd.Timestamp("2025-01-10", tz="UTC"),
                entry_price=100.0,
                exit_price=98.0,
                size=1.0,
                net_pnl=-2.0,
            ),
        ]

        result = StrategyResult(
            trades=trades,
            equity_curve=[100.0, 95.0, 95.0, 90.0, 100.0, 98.0],
            balance_curve=[100.0, 95.0, 95.0, 90.0, 100.0, 98.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")] * 6,
        )

        basic = calculate_basic(result, initial_balance=100.0)
        assert basic.max_consecutive_losses == 3

    def test_calculate_sqn_sufficient_trades(self):
        trades = [
            TradeRecord(net_pnl=100 + i) for i in range(30)
        ]
        sqn = _calculate_sqn_value(trades)
        assert sqn is not None
        assert isinstance(sqn, float)

    def test_calculate_sqn_insufficient_trades(self):
        trades = [TradeRecord(net_pnl=100) for _ in range(29)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is None

    def test_calculate_sqn_zero_variance(self):
        trades = [TradeRecord(net_pnl=100) for _ in range(30)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is None

    def test_calculate_sqn_negative_expectancy(self):
        trades = [TradeRecord(net_pnl=-(10 + i)) for i in range(30)]
        sqn = _calculate_sqn_value(trades)
        assert sqn is not None
        assert sqn < 0


class TestStableSharpeAndSqn:
    def test_sharpe_welford_matches_population_oracle(self):
        rng = np.random.default_rng(20260803)
        monthly_returns = rng.normal(1.5, 3.0, 120).tolist()
        expected = (
            float(np.mean(monthly_returns)) - (0.02 * 100.0) / 12.0
        ) / float(np.std(monthly_returns, ddof=0))

        assert _calculate_sharpe_ratio_value(monthly_returns) == pytest.approx(
            expected,
            rel=1e-14,
            abs=1e-14,
        )

    def test_sharpe_exact_constant_is_undefined(self):
        assert _calculate_sharpe_ratio_value([1.25] * 24) is None

    def test_sharpe_large_mean_tiny_variance_remains_finite(self):
        monthly_returns = [1_000_000_000.0 + offset for offset in (0.0, 1e-5, -1e-5, 2e-5)]
        count, mean, m2 = _welford_mean_m2(monthly_returns)
        value = _calculate_sharpe_ratio_value(monthly_returns)

        assert count == 4
        assert mean > 0.0
        assert m2 > 0.0
        assert value is not None and math.isfinite(value)

    def test_sharpe_two_month_minimum_and_negative_value(self):
        assert _calculate_sharpe_ratio_value([1.0]) is None
        assert _calculate_sharpe_ratio_value([-2.0, -1.0]) < 0.0

    def test_sharpe_non_finite_input_is_undefined(self):
        assert _calculate_sharpe_ratio_value([1.0, math.nan]) is None

    def test_sqn_uses_exact_net_pnl_including_commissions(self):
        net_pnls = [10.0 + index - (0.25 + 0.5) for index in range(30)]
        trades = [
            TradeRecord(entry_price=100.0, exit_price=110.0, size=1.0, net_pnl=value)
            for value in net_pnls
        ]
        expected = math.sqrt(30) * float(np.mean(net_pnls)) / float(np.std(net_pnls, ddof=1))

        assert _calculate_sqn_value(trades) == pytest.approx(expected, rel=1e-14, abs=1e-14)

    def test_sqn_tiny_variance_and_non_finite_are_undefined(self):
        tiny_variance = [TradeRecord(net_pnl=1.0 + (5e-11 if index % 2 else -5e-11)) for index in range(30)]
        non_finite = [TradeRecord(net_pnl=float(index)) for index in range(29)] + [
            TradeRecord(net_pnl=math.nan)
        ]

        assert _calculate_sqn_value(tiny_variance) is None
        assert _calculate_sqn_value(non_finite) is None


class TestAdvancedMetricBoundary:
    @staticmethod
    def _trade() -> TradeRecord:
        return TradeRecord(net_pnl=1.0)

    @staticmethod
    def _result(
        equity,
        timestamps,
        *,
        metric_start_idx=0,
        metric_initial_equity=100.0,
        trades=None,
    ):
        return StrategyResult(
            trades=[TestAdvancedMetricBoundary._trade()] if trades is None else trades,
            equity_curve=list(equity),
            balance_curve=list(equity),
            timestamps=list(timestamps),
            metric_start_idx=metric_start_idx,
            metric_initial_equity=metric_initial_equity,
        )

    @pytest.mark.parametrize("first_equity", [99.5, 110.0, 90.0])
    def test_boundary_zero_explicit_anchor_captures_first_bar(self, first_equity):
        timestamps = pd.to_datetime(
            ["2025-01-31T23:30:00Z", "2025-02-01T00:00:00Z"]
        )
        result = self._result([first_equity, 108.0], timestamps)
        view = _advanced_metric_view(result)
        returns = _calculate_monthly_returns(
            view.equity_observations,
            view.timestamps,
            initial_equity=view.initial_equity,
        )

        assert view.initial_equity == 100.0
        assert view.equity_path.tolist() == [100.0, first_equity, 108.0]
        assert returns[0] == pytest.approx((first_equity / 100.0 - 1.0) * 100.0)
        assert returns[1] == pytest.approx((108.0 / first_equity - 1.0) * 100.0)
        assert math.prod(1.0 + value / 100.0 for value in returns) == pytest.approx(1.08)

    def test_anchor_participates_in_ulcer_and_consistency_paths(self):
        timestamps = pd.date_range("2025-01-01", periods=3, freq="D", tz="UTC")
        result = self._result([90.0, 95.0, 110.0], timestamps)
        advanced = calculate_advanced(result)
        expected_path = [100.0, 90.0, 95.0, 110.0]

        assert advanced.ulcer_index == pytest.approx(
            _calculate_ulcer_index_value(expected_path)
        )
        assert advanced.consistency_score == pytest.approx(
            _calculate_r2_consistency(expected_path)
        )

    def test_warmup_prefix_length_and_calendar_span_do_not_change_metrics(self):
        evaluation_timestamps = pd.to_datetime(
            [
                "2025-03-01T00:00:00Z",
                "2025-03-31T23:30:00Z",
                "2025-04-01T00:00:00Z",
                "2025-05-15T00:00:00Z",
            ]
        )
        evaluation_equity = [99.5, 105.0, 102.0, 115.0]
        results = []
        for prefix_len, frequency in ((0, "30min"), (100, "15min"), (1000, "1D")):
            if prefix_len:
                prefix_timestamps = pd.date_range(
                    end=evaluation_timestamps[0] - pd.Timedelta(frequency),
                    periods=prefix_len,
                    freq=frequency,
                )
            else:
                prefix_timestamps = pd.DatetimeIndex([])
            results.append(
                self._result(
                    [100.0] * prefix_len + evaluation_equity,
                    list(prefix_timestamps) + list(evaluation_timestamps),
                    metric_start_idx=prefix_len,
                )
            )

        affected = ("sharpe_ratio", "sortino_ratio", "ulcer_index", "consistency_score")
        expected = calculate_advanced(results[0]).to_dict()
        for result in results[1:]:
            actual = calculate_advanced(result).to_dict()
            assert {name: actual[name] for name in affected} == pytest.approx(
                {name: expected[name] for name in affected}
            )

    @pytest.mark.parametrize(
        ("metric_start_idx", "metric_initial_equity", "message"),
        [
            (-1, 100.0, "metric_start_idx"),
            (3, 100.0, "metric_start_idx"),
            (True, 100.0, "metric_start_idx"),
            (0, math.nan, "metric_initial_equity"),
            (0, math.inf, "metric_initial_equity"),
            (0, -1.0, "metric_initial_equity"),
        ],
    )
    def test_malformed_boundary_facts_fail_clearly(
        self,
        metric_start_idx,
        metric_initial_equity,
        message,
    ):
        result = self._result(
            [100.0, 101.0],
            pd.date_range("2025-01-01", periods=2, freq="D", tz="UTC"),
            metric_start_idx=metric_start_idx,
            metric_initial_equity=metric_initial_equity,
        )
        with pytest.raises(ValueError, match=message):
            calculate_advanced(result)

    def test_inconsistent_timestamp_and_equity_lengths_fail_clearly(self):
        result = self._result(
            [100.0, 101.0],
            [pd.Timestamp("2025-01-01", tz="UTC")],
            trades=[],
        )
        with pytest.raises(ValueError, match="timestamps.*equity_curve"):
            calculate_advanced(result)

    def test_empty_and_boundary_equal_to_result_length_are_supported(self):
        empty = self._result([], [], metric_initial_equity=100.0, trades=[])
        view = _advanced_metric_view(empty)
        assert view.initial_equity == 100.0
        assert view.equity_observations.size == 0
        assert view.equity_path.tolist() == [100.0]
        empty_advanced = calculate_advanced(empty)
        assert empty_advanced.ulcer_index is None
        assert empty_advanced.consistency_score is None

        timestamps = pd.date_range("2025-01-01", periods=2, freq="D", tz="UTC")
        warmup_only = self._result(
            [100.0, 100.0],
            timestamps,
            metric_start_idx=2,
            metric_initial_equity=None,
            trades=[],
        )
        view = _advanced_metric_view(warmup_only)
        assert view.initial_equity == 100.0
        assert view.equity_observations.size == 0
        warmup_only_advanced = calculate_advanced(warmup_only)
        assert warmup_only_advanced.sharpe_ratio is None
        assert warmup_only_advanced.ulcer_index is None
        assert warmup_only_advanced.consistency_score is None

    @pytest.mark.parametrize("observation_count", [1, 3])
    def test_genuine_flat_evaluation_observations_keep_zero_path_metrics(
        self,
        observation_count,
    ):
        timestamps = pd.date_range(
            "2025-01-01",
            periods=observation_count,
            freq="D",
            tz="UTC",
        )
        result = self._result(
            [100.0] * observation_count,
            timestamps,
            trades=[],
        )

        advanced = calculate_advanced(result)

        assert advanced.ulcer_index == 0.0
        if observation_count == 1:
            assert advanced.consistency_score is None
        else:
            assert advanced.consistency_score == 0.0

    def test_zero_trade_metrics_validate_lengths_without_calendar_materialization(
        self,
        monkeypatch,
    ):
        timestamps = [
            "2025-01-01T00:00:00Z",
            "2025-02-01T00:00:00Z",
        ]
        result = self._result([100.0, 100.0], timestamps, trades=[])

        def fail_datetime_index(*args, **kwargs):
            raise AssertionError("zero-trade metrics must not normalize timestamps")

        monkeypatch.setattr(metrics_module.pd, "DatetimeIndex", fail_datetime_index)

        advanced = calculate_advanced(result)

        assert advanced.sharpe_ratio is None
        assert advanced.ulcer_index == 0.0
        assert advanced.consistency_score == 0.0

    def test_trade_bearing_string_timestamps_normalize_for_monthly_metrics(self):
        result = self._result(
            [110.0, 121.0, 133.1],
            [
                "2025-01-31T23:30:00Z",
                "2025-02-01T00:00:00Z",
                "2025-03-01T00:00:00Z",
            ],
        )
        view = _advanced_metric_view(result)

        returns = _calculate_monthly_returns(
            view.equity_observations,
            view.timestamps,
            initial_equity=view.initial_equity,
        )
        advanced = calculate_advanced(result)

        assert returns == pytest.approx([10.0, 10.0, 10.0])
        assert advanced.sharpe_ratio is not None

    def test_production_anchor_makes_advanced_metrics_caller_independent(self):
        timestamps = pd.to_datetime(
            ["2025-01-31T23:30:00Z", "2025-02-01T00:00:00Z", "2025-02-28T23:30:00Z"]
        )
        result = self._result([99.0, 101.0, 108.0], timestamps)

        without_argument = calculate_advanced(result).to_dict()
        with_argument = calculate_advanced(result, initial_balance=999.0).to_dict()
        affected = ("sharpe_ratio", "sortino_ratio", "ulcer_index", "consistency_score")
        assert {name: without_argument[name] for name in affected} == pytest.approx(
            {name: with_argument[name] for name in affected}
        )

    def test_legacy_boundary_zero_preserves_established_path_behavior(self):
        equity = [100.0, 90.0, 110.0]
        timestamps = pd.date_range("2025-01-01", periods=3, freq="D", tz="UTC")
        result = StrategyResult(
            trades=[self._trade()],
            equity_curve=equity,
            balance_curve=equity,
            timestamps=list(timestamps),
        )
        view = _advanced_metric_view(result)

        assert view.initial_equity == 100.0
        assert view.equity_path.tolist() == equity
        assert calculate_advanced(result).ulcer_index == pytest.approx(
            _calculate_ulcer_index_value(equity)
        )

    @pytest.mark.parametrize(
        ("timestamps", "equity", "expected"),
        [
            (
                ["2025-10-01T00:00:00Z", "2025-10-31T23:30:00Z", "2025-11-30T23:30:00Z"],
                [101.0, 110.0, 121.0],
                [10.0, 10.0],
            ),
            (
                ["2025-10-15T00:00:00Z", "2025-11-01T00:00:00Z", "2025-12-14T23:30:00Z"],
                [90.0, 99.0, 108.9],
                [-10.0, 10.0, 10.0],
            ),
            (
                ["2023-12-31T23:30:00Z", "2024-01-01T00:00:00Z", "2024-02-29T23:30:00Z"],
                [105.0, 100.0, 110.0],
                [5.0, (100.0 / 105.0 - 1.0) * 100.0, 10.0],
            ),
        ],
    )
    def test_month_boundaries_partial_periods_and_calendar_edges(
        self,
        timestamps,
        equity,
        expected,
    ):
        actual = _calculate_monthly_returns(
            equity,
            pd.DatetimeIndex(pd.to_datetime(timestamps)),
            initial_equity=100.0,
        )
        assert actual == pytest.approx(expected)


class TestR2Consistency:
    """Unit tests for the signed R² consistency metric."""

    def test_perfect_compounded_growth_returns_positive_one(self):
        equity = [100.0, 110.0, 121.0, 133.1, 146.41]
        assert _calculate_r2_consistency(equity) == pytest.approx(1.0)

    def test_perfect_compounded_decline_returns_negative_one(self):
        equity = [146.41, 133.1, 121.0, 110.0, 100.0]
        assert _calculate_r2_consistency(equity) == pytest.approx(-1.0)

    def test_same_shape_different_scale_returns_same_score(self):
        eq_small = [100.0, 110.0, 121.0, 133.1, 146.41]
        eq_large = [1000.0, 1100.0, 1210.0, 1331.0, 1464.1]
        assert _calculate_r2_consistency(eq_small) == pytest.approx(
            _calculate_r2_consistency(eq_large),
            abs=1e-12,
        )

    def test_flat_curve_returns_zero(self):
        assert _calculate_r2_consistency([100.0] * 10) == pytest.approx(0.0)

    def test_raw_equity_fallback_handles_non_positive_curves(self):
        equity = [-10.0, -5.0, 0.0, 5.0, 10.0]
        assert _calculate_r2_consistency(equity) == pytest.approx(1.0)

    def test_positive_endpoint_does_not_force_positive_sign(self):
        equity = [100.0, 80.0, 60.0, 40.0, 101.0]
        score = _calculate_r2_consistency(equity)
        assert score is not None
        assert score < 0.0

    def test_invalid_input_returns_none(self):
        assert _calculate_r2_consistency([]) is None
        assert _calculate_r2_consistency([100.0, 110.0]) is None
        assert _calculate_r2_consistency([100.0, float("nan"), 120.0]) is None


class TestMetricsRegression:
    """Regression checks against recorded baseline values."""

    def test_baseline_basic_matches(self, test_result, baseline_params):
        _, baseline = baseline_params
        expected_net_profit_pct = baseline["net_profit_pct"]
        expected_max_dd_pct = baseline["max_drawdown_pct"]
        expected_trades = baseline["total_trades"]

        basic = calculate_basic(test_result)

        assert abs(basic.net_profit_pct - expected_net_profit_pct) < 0.01
        assert abs(basic.max_drawdown_pct - expected_max_dd_pct) < 0.01
        assert basic.total_trades == expected_trades

    def test_baseline_advanced_matches(self, test_result, baseline_params):
        _, baseline = baseline_params
        advanced = calculate_advanced(test_result)

        assert abs((advanced.sharpe_ratio or 0) - baseline["sharpe_ratio"]) < 1e-6
        assert abs((advanced.profit_factor or 0) - baseline["profit_factor"]) < 1e-6
        assert abs((advanced.romad or 0) - baseline["romad"]) < 1e-6
        baseline_sqn = baseline.get("sqn")
        if baseline_sqn is None:
            assert advanced.sqn is None
        else:
            assert abs((advanced.sqn or 0) - baseline_sqn) < 1e-6
        assert abs((advanced.ulcer_index or 0) - baseline["ulcer_index"]) < 1e-6
        assert abs((advanced.consistency_score or 0) - baseline["consistency_score"]) < 1e-6


class TestEnrichStrategyResult:
    """Test the enrich_strategy_result helper and drift guards."""

    def test_enrich_attaches_declared_fields(self):
        """Verify declared StrategyResult fields are populated."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0, 105.0, 110.0],
            balance_curve=[100.0, 105.0, 110.0],
            timestamps=[
                pd.Timestamp("2025-01-01", tz="UTC"),
                pd.Timestamp("2025-01-02", tz="UTC"),
                pd.Timestamp("2025-01-03", tz="UTC"),
            ],
        )

        basic, advanced = enrich_strategy_result(result, initial_balance=100.0)

        # Verify declared fields are attached correctly
        assert result.net_profit == pytest.approx(basic.net_profit)
        assert result.net_profit_pct == pytest.approx(basic.net_profit_pct)
        assert result.max_drawdown_pct == pytest.approx(basic.max_drawdown_pct)
        assert result.total_trades == basic.total_trades

    def test_drift_guard_win_rate_not_attached(self):
        """win_rate exists in BasicMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        # win_rate should NOT be attached (not declared in StrategyResult)
        assert not hasattr(result, "win_rate")

    def test_drift_guard_sortino_not_attached(self):
        """sortino_ratio exists in AdvancedMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        # sortino_ratio should NOT be attached (not declared in StrategyResult)
        assert not hasattr(result, "sortino_ratio")

    def test_drift_guard_avg_metrics_not_attached(self):
        """avg_win, avg_loss, avg_trade exist in BasicMetrics but NOT in StrategyResult."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        enrich_strategy_result(result, initial_balance=100.0)

        assert not hasattr(result, "avg_win")
        assert not hasattr(result, "avg_loss")
        assert not hasattr(result, "avg_trade")

    def test_returns_both_metric_objects(self):
        """Helper returns BasicMetrics and AdvancedMetrics for full access."""
        from core.metrics import enrich_strategy_result

        result = StrategyResult(
            trades=[],
            equity_curve=[100.0],
            balance_curve=[100.0],
            timestamps=[pd.Timestamp("2025-01-01", tz="UTC")],
        )

        basic, advanced = enrich_strategy_result(result, initial_balance=100.0)

        # Callers can access optimization-only metrics from returned objects
        assert hasattr(basic, "win_rate")
        assert hasattr(basic, "avg_win")
        assert hasattr(advanced, "sortino_ratio")
